[features]
resolution = true
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
vokter_wallet = "9w9B3s4CvdaVZoGhj25UmPz1wzV9tCHNhCwGyDFqmcrw"

[programs.devnet]
vokter_wallet = "9w9B3s4CvdaVZoGhj25UmPz1wzV9tCHNhCwGyDFqmcrw"

[programs.mainnet]
vokter_wallet = "9w9B3s4CvdaVZoGhj25UmPz1wzV9tCHNhCwGyDFqmcrw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/santo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metaplex_token_metadata.so"